Proyecto/djangobasico/djangobasico/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favoritos.urls'))
]

Proyecto/djangobasico/favoritos/urls.py
from django.urls import path, include
from .views import *
app_name = 'favoritos'
urlpatterns = [
    path('', index_favoritos, name='index'),
    path('crear/', crear_favorito, name='crear'),
    path('borrar/<int:pk>', borrar_favorito, name="borrar"),
    path('detalle/<int:pk>', detalle_favorito, name="detalle"),
    path('actualizar/<int:pk>', actualizar_favorito, name="actualizar"),
]

Proyecto/djangobasico/favoritos/models.py
from django.db import models

# Create your models here.
class Favoritos(models.Model):
    nombre = models.CharField(max_length=100)
    url = models.URLField(max_length=200)

Proyecto/djangobasico/favoritos/forms.py
from django.forms import ModelForm
from .models import *


class FavoriteModelForm(ModelForm):
    class Meta:
        model = Favoritos
        fields = '__all__'

Proyecto/djangobasico/favoritos/views.py
from distutils.command.config import config
from lib2to3.fixes.fix_input import context

from django.shortcuts import render, redirect
from .forms import *

# Create your views here.
def index_favoritos(request):
    favoritos_lista = Favoritos.objects.all()
    context = {
        'favoritos_lista': favoritos_lista
    }
    return render(request, 'favoritos/lista.html', context)


def crear_favorito(request):
    form = FavoriteModelForm()

    if request.method == 'POST':
        form = FavoriteModelForm(request.POST)
        if form.is_valid():
            form.save()
        else :
            print(form.errors)

    context = {
        'form': form,
        'titulo': 'Crear favorito',
    }
    return render(request, 'favoritos/crear.html', context)

def detalle_favorito(request, pk):
    favorito= Favoritos.objects.get(pk=pk)
    context = {
        'favorito': favorito
    }
    return render(request, 'favoritos/detalle.html', context )

def borrar_favorito(request, pk):
    Favoritos.objects.get(pk=pk).delete()
    return redirect('favoritos:index')

def actualizar_favorito(request, pk):
    favorito = Favoritos.objects.get(pk=pk)
    form = FavoriteModelForm(instance=favorito)

    if request.method == 'POST':
        form = FavoriteModelForm(request.POST, instance=favorito)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)

    context = {
        'form': form,
        'titulo': 'Actualizar favorito',
    }
    return render(request, 'favoritos/crear.html', context)

Proyecto/djangobasico/favoritos/templates/favoritos/crear.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crear Favoritos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>{{ titulo }}</h1>
    <a class="btn btn-primary" href="{% url 'favoritos:index' %}" role="button">Atras</a>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

Proyecto/djangobasico/favoritos/templates/favoritos/detalle.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crear Favoritos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>Detalle Favorito</h1>
    <p>{{ favorito.nombre }}</p>
    <p> {{ favorito.url }}</p>
    <a class="btn btn-primary" href="{% url 'favoritos:index' %}" role="button">Atras</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

Proyecto/djangobasico/favoritos/templates/favoritos/lista.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lista Favoritos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>Lista Favoritos</h1>
    <a class="btn btn-outline-warning" href="{% url 'favoritos:crear' %}" role="button">Nuevo</a>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombre</th>
            <th scope="col">URL</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
            {% for favorito in favoritos_lista %}
                <tr>
                <th scope="row">{{ favorito.id }}</th>
                <td>{{ favorito.nombre }}</td>
                <td>{{ favorito.url }}</td>
                <td> <a href="{% url 'favoritos:borrar' favorito.pk %}">Borrar</a> </td>
                <td> <a href="{% url 'favoritos:detalle' favorito.pk %}">Detalle</a> </td>
                <td> <a href="{% url 'favoritos:actualizar' favorito.pk %}">Actualizar</a> </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

Proyecto/djangobasico/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>